export const DEFAULT_LIGHT_THEME: Record<string, string> = {
  '--primary': '#0369a1',
  '--on-primary': '#ffffff',
  '--primary-container': '#e0f2fe',
  '--on-primary-container': '#07284b',
  '--secondary': '#0284c7',
  '--on-secondary': '#ffffff',
  '--tertiary': '#4f46e5',
  '--background': '#ffffff',
  '--on-background': '#0f172a',
  '--surface': '#f8f9ff',
  '--surface-dim': '#ccdbf3',
  '--surface-bright': '#ffffff',
  '--surface-container-lowest': '#ffffff',
  '--surface-container-low': '#eff4ff',
  '--surface-container': '#e0eaff',
  '--surface-container-high': '#d1e0ff',
  '--surface-container-highest': '#c2d6ff',
  '--on-surface': '#0f172a',
  '--on-surface-variant': '#475569',
  '--outline': '#94a3b8',
  '--outline-variant': '#cbd5e1',
  '--error': '#dc2626',
  '--on-error': '#ffffff',
  '--error-container': '#fee2e2',
  '--on-error-container': '#991b1b',
  '--on-primary-fixed-variant': '#0284c7',
  '--on-tertiary-container': '#312e81',
  '--secondary-fixed-dim': '#38bdf8',
  '--secondary-container': '#e0f2fe',
  '--primary-fixed-dim': '#38bdf8',
  '--primary-fixed': '#bae6fd',
  '--on-tertiary-fixed': '#ffffff',
  '--surface-tint': '#0369a1',
  '--tertiary-fixed-dim': '#818cf8',
  '--on-tertiary-fixed-variant': '#3730a3',
  '--surface-variant': '#f1f5f9',
  '--inverse-surface': '#1e293b',
  '--tertiary-fixed': '#c7d2fe',
  '--secondary-fixed': '#bae6fd',
  '--on-secondary-fixed': '#ffffff',
  '--inverse-on-surface': '#f8fafc',
  '--on-tertiary': '#ffffff',
  '--on-primary-fixed': '#ffffff',
  '--on-secondary-fixed-variant': '#0284c7',
  '--inverse-primary': '#38bdf8',
  '--on-secondary-container': '#0c4a6e',
  '--tertiary-container': '#e0e7ff',
  '--quo-bg': '#FFFFFF',
  '--quo-surface': '#1B1C1D',
  '--quo-surface-alt': '#F9F7F5',
  '--quo-primary': '#9D7E6C',
  '--quo-border': '#e2e2e2',
  '--quo-text': '#1a1c1c',
  '--quo-text-muted': '#74777c',
};

export const DEFAULT_DARK_THEME: Record<string, string> = {
  '--primary': '#7dd3fc',
  '--on-primary': '#001f2e',
  '--primary-container': '#0e4d6e',
  '--on-primary-container': '#c8eaff',
  '--secondary': '#88b4cc',
  '--on-secondary': '#001f2e',
  '--tertiary': '#c8a0f0',
  '--background': '#0a0e1a',
  '--on-background': '#e0e8f0',
  '--surface': '#0f1524',
  '--surface-dim': '#0f1524',
  '--surface-bright': '#1a2438',
  '--surface-container-lowest': '#0a0e1a',
  '--surface-container-low': '#111828',
  '--surface-container': '#141c2e',
  '--surface-container-high': '#1a2438',
  '--surface-container-highest': '#202c42',
  '--on-surface': '#e0e8f0',
  '--on-surface-variant': '#a0b4c4',
  '--outline': '#4a6070',
  '--outline-variant': '#2a3a48',
  '--error': '#ff6b6b',
  '--on-error': '#1a0000',
  '--error-container': '#3d1414',
  '--on-error-container': '#ffb3b3',
  '--on-primary-fixed-variant': '#004d73',
  '--on-tertiary-container': '#e8d0ff',
  '--secondary-fixed-dim': '#88b4cc',
  '--secondary-container': '#1a3a4e',
  '--primary-fixed-dim': '#7dd3fc',
  '--primary-fixed': '#c8eaff',
  '--on-tertiary-fixed': '#1a002e',
  '--surface-tint': '#7dd3fc',
  '--tertiary-fixed-dim': '#c8a0f0',
  '--on-tertiary-fixed-variant': '#4d2a73',
  '--surface-variant': '#1a2438',
  '--inverse-surface': '#e0e8f0',
  '--tertiary-fixed': '#e8d0ff',
  '--secondary-fixed': '#c0d8e8',
  '--on-secondary-fixed': '#0d1f2b',
  '--inverse-on-surface': '#0a0e1a',
  '--on-tertiary': '#1a002e',
  '--on-primary-fixed': '#001f2e',
  '--on-secondary-fixed-variant': '#2a4a5e',
  '--inverse-primary': '#0a4c6e',
  '--on-secondary-container': '#c0d8e8',
  '--tertiary-container': '#3d2060',
  '--quo-bg': '#FFFFFF',
  '--quo-surface': '#1B1C1D',
  '--quo-surface-alt': '#F9F7F5',
  '--quo-primary': '#9D7E6C',
  '--quo-border': '#e2e2e2',
  '--quo-text': '#1a1c1c',
  '--quo-text-muted': '#74777c',
};

export const THEME_SECTIONS = [
  {
    title: 'Brand Colors',
    keys: [
      { name: 'Primary', key: '--primary', desc: 'Main brand color for buttons, active states, and highlights' },
      { name: 'On Primary', key: '--on-primary', desc: 'Text and icon color displayed on top of the primary color' },
      { name: 'Secondary', key: '--secondary', desc: 'Used for less prominent UI elements and secondary actions' },
      { name: 'On Secondary', key: '--on-secondary', desc: 'Text color displayed on top of the secondary color' },
      { name: 'Tertiary', key: '--tertiary', desc: 'Used for contrasting accents that balance primary and secondary colors' },
      { name: 'On Tertiary', key: '--on-tertiary', desc: 'Text color displayed on top of the tertiary color' },
    ],
  },
  {
    title: 'Primary Variations',
    keys: [
      { name: 'Primary Container', key: '--primary-container', desc: 'A softer background fill for primary-colored elements' },
      { name: 'On Primary Container', key: '--on-primary-container', desc: 'Text color used inside a primary container' },
      { name: 'Primary Fixed', key: '--primary-fixed', desc: 'A fixed primary color that ignores dark mode inversions' },
      { name: 'Primary Fixed Dim', key: '--primary-fixed-dim', desc: 'A slightly darker variation of the fixed primary color' },
      { name: 'Inverse Primary', key: '--inverse-primary', desc: 'Primary color used on inverted backgrounds (e.g. snackbars)' },
    ],
  },
  {
    title: 'Secondary/Tertiary Variations',
    keys: [
      { name: 'Secondary Container', key: '--secondary-container', desc: 'A softer background fill for secondary-colored elements' },
      { name: 'On Secondary Container', key: '--on-secondary-container', desc: 'Text color used inside a secondary container' },
      { name: 'Tertiary Container', key: '--tertiary-container', desc: 'A softer background fill for tertiary-colored elements' },
      { name: 'On Tertiary Container', key: '--on-tertiary-container', desc: 'Text color used inside a tertiary container' },
    ],
  },
  {
    title: 'Backgrounds & Surfaces',
    keys: [
      { name: 'Background', key: '--background', desc: 'The default background color for the main app canvas' },
      { name: 'On Background', key: '--on-background', desc: 'Text color used directly on the main background' },
      { name: 'Surface', key: '--surface', desc: 'Background color for cards, sheets, and menus' },
      { name: 'Surface Dim', key: '--surface-dim', desc: 'A slightly darker surface color for subtle contrast' },
      { name: 'Surface Bright', key: '--surface-bright', desc: 'A slightly lighter surface color for elevated contrast' },
      { name: 'Surface Tint', key: '--surface-tint', desc: 'A tint applied to surfaces to indicate elevation' },
      { name: 'Surface Variant', key: '--surface-variant', desc: 'An alternative surface color for distinct UI sections' },
    ],
  },
  {
    title: 'Surface Containers',
    keys: [
      { name: 'Lowest Container', key: '--surface-container-lowest', desc: 'The lightest possible container background (lowest elevation)' },
      { name: 'Low Container', key: '--surface-container-low', desc: 'A subtle container background, often used for flat lists' },
      { name: 'Container', key: '--surface-container', desc: 'The standard container background for general grouping' },
      { name: 'High Container', key: '--surface-container-high', desc: 'A slightly emphasized container background' },
      { name: 'Highest Container', key: '--surface-container-highest', desc: 'The most emphasized container background (e.g. distinct inputs)' },
    ],
  },
  {
    title: 'Text & Outlines',
    keys: [
      { name: 'On Surface', key: '--on-surface', desc: 'Primary text color used on top of most surface elements' },
      { name: 'On Surface Variant', key: '--on-surface-variant', desc: 'Secondary or muted text color on surface elements' },
      { name: 'Outline', key: '--outline', desc: 'Standard border and divider color' },
      { name: 'Outline Variant', key: '--outline-variant', desc: 'Lighter or more subtle border color for decorative dividers' },
    ],
  },
  {
    title: 'Feedback (Errors)',
    keys: [
      { name: 'Error', key: '--error', desc: 'Main color used to indicate destructive actions or invalid states' },
      { name: 'On Error', key: '--on-error', desc: 'Text color used on top of the error color' },
      { name: 'Error Container', key: '--error-container', desc: 'A softer background fill for error messages or alerts' },
      { name: 'On Error Container', key: '--on-error-container', desc: 'Text color used inside an error container' },
    ],
  },
];

export const QUOTATION_THEME_SECTIONS = [
  {
    title: 'Backgrounds & Surfaces',
    keys: [
      { name: 'Document Background', key: '--quo-bg', desc: 'Main background of the PDF' },
      { name: 'Header/Footer Surface', key: '--quo-surface', desc: 'Dark background used in headers, footers, and table headings' },
      { name: 'Table Row Background', key: '--quo-surface-alt', desc: 'Background color of the items table rows' },
    ],
  },
  {
    title: 'Brand & Accents',
    keys: [
      { name: 'Primary Accent', key: '--quo-primary', desc: 'Accent color for taglines, bullet points, and highlights' },
      { name: 'Borders & Dividers', key: '--quo-border', desc: 'Color of table borders and section dividers' },
    ],
  },
  {
    title: 'Typography',
    keys: [
      { name: 'Main Text', key: '--quo-text', desc: 'Primary text color for titles, item names, and important details' },
      { name: 'Muted Text', key: '--quo-text-muted', desc: 'Secondary text color for descriptions and subtle information' },
    ],
  },
];
